export const formBlockDefaults = {
  root: 'w-full py-12 bg-white',
  container: 'max-w-5xl mx-auto px-6',
  panel: 'grid grid-cols-1 gap-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-900/5 md:grid-cols-[0.85fr_1.15fr] md:p-8',
  introColumn: 'space-y-4',
  eyebrow: 'text-sm font-bold uppercase text-sky-700',
  heading: 'text-3xl font-extrabold leading-tight text-slate-950',
  intro: 'text-base leading-7 text-slate-600',
  form: 'space-y-5',
  fieldGrid: 'grid grid-cols-1 gap-4 sm:grid-cols-2',
  fieldWrapper: 'block',
  fieldWrapperFull: 'block sm:col-span-2',
  fieldLabel: 'mb-1.5 block text-sm font-bold text-slate-800',
  requiredMark: 'text-sky-700',
  fieldInput: 'w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-sm text-slate-950 outline-none transition placeholder:text-slate-400 focus:border-sky-600 focus:bg-white focus:ring-2 focus:ring-sky-200',
  fieldTextarea: 'min-h-[130px] w-full resize-y rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-sm text-slate-950 outline-none transition placeholder:text-slate-400 focus:border-sky-600 focus:bg-white focus:ring-2 focus:ring-sky-200',
  fieldCheckbox: 'flex items-start gap-3 rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-sm text-slate-800',
  checkboxInput: 'mt-1 h-4 w-4 rounded border-slate-300 text-sky-700 focus:ring-sky-500',
  helpText: 'mt-1.5 block text-xs text-slate-500',
  honeypot: 'absolute left-[-10000px] top-auto h-px w-px overflow-hidden',
  status: 'rounded-2xl px-4 py-3 text-sm font-semibold outline-none',
  statusSuccess: 'border border-emerald-200 bg-emerald-50 text-emerald-800',
  statusError: 'border border-red-200 bg-red-50 text-red-800',
  statusPending: 'border border-sky-200 bg-sky-50 text-sky-800',
  submitButton: 'inline-flex min-h-12 w-fit items-center justify-center rounded-full bg-sky-700 px-6 py-3 text-sm font-bold text-white shadow-lg shadow-sky-900/15 transition hover:bg-sky-800 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:bg-slate-400 disabled:shadow-none',
  missing: 'rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900',
};

export type FormBlockClassNames = Partial<typeof formBlockDefaults>;
